# Generated by Django 4.1.5 on 2023-01-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d/')),
                ('facebook', models.URLField(max_length=255)),
                ('twitter', models.URLField(max_length=255)),
                ('googleplus', models.URLField(max_length=255)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
